export default [
  "Bank Limited",
  "Agrani Bank Limited",
  "Al-Arafah Islami Bank Limited",
  "Bangladesh Commerce Bank Limited",
  "Bangladesh Development Bank Limited",
  "Bangladesh Krishi Bank",
  "Bank Al-Falah Limited",
  "Bank Asia Limited",
  "BASIC Bank Limited",
  "Bengal Commercial Bank Ltd",
  "BRAC Bank Limited",
  "Citibank N.A",
  "City Bank Limited",
  "Commercial Bank of Ceylon PLABC" ,
  "Community Bank Bangladesh Limited",
  "Dhaka Bank Limited",
  "Dutch-Bangla Bank Limited",
  "Eastern Bank Limited",
  "EXIM Bank Limited",
  "First Security Islami Bank Limited",
  "Habib Bank Limited" ,
  "HSBC",
  "ICB Islamic Bank Limited",
  "IFIC Bank Limited",
  "Islami Bank Bangladesh Limited",
  "Jamuna Bank Limited",
  "Janata Bank Limited",
  "Meghna Bank Limited",
  "Mercantile Bank Limited",
  "Midland Bank Limited",
  "Modhumoti Bank Limited",
  "Mutual Trust Bank Limited",
  "National Bank Limited",
  "National Bank of Pakistan",
  "National Credit & Commerce Bank Limited",
  "NRB Bank Limited",
  "NRB Commercial Bank Ltd",
  "NRB Global Bank Ltd",
  "One Bank Limited",
  "Padma Bank Limited",
  "Premier Bank Limited",
  "Prime Bank Limited",
  "Probashi Kallyan Bank",
  "Pubali Bank Limited",
  "Rajshahi Krishi Unnayan Bank",
  "Rupali Bank Limited",
  "Shahjalal Islami Bank Limited",
  "Shimanto Bank Ltd",
  "Social Islami Bank Limited",
  "Sonali Bank Limited",
  "South Bangla Agriculture and Commerce Bank Limited",
  "Southeast Bank Limited",
  "Standard Bank Limited",
  "Standard Chartered Bank" ,
  "State Bank of India",
  "Trust Bank Limited",
  "Union Bank Ltd",
  "United Commercial Bank Ltd",
  "Uttara Bank Limited",
  "Woori Bank",
]